paul-hammant/tbd

content/game-changers/index.md

spelling issue fixed

---

content/game-changers/index.md

language cleanup in the section on Apache's Gump

---

content/feature-flags/index.md

couple of typo fixes

---

content/index.md

I've spent too long in government. That's a trigger word ;)

Rename portal to site

---

content/context/index.md

Address some grammar and spelling issues.

Address grammar and spelling

---

content/deciding-factors/index.md

I believe that the intended meaning was tenet, i.e. principle.

Minor word fix

---

content/concurrent-development-of-consecutive-releases/index.md

Paul, I thing the Perforce has changed the link of talk

Link  of perforce talk

---

config.toml
content/context/index.md

Dear Paul,
here is one more contribution.

Translation to pt

---

content/vcs-choices/index.md

I've added the Visual Studio Team Services platform as a new way to use git in the cloud.

Added vsts to git platform choices

---

content/observed-habits/index.md

Modifying the sentences in the section to more smoothly.

Fixing sentence structure in Facilitating Commits section 

---

content/committing-straight-to-the-trunk/index.md

remove unnecessary line break

---

content/5-min-overview/index.md

Update 5 min overview

---

content/observed-habits/index.md

Update 'observed habits'

---

content/vcs-features/index.md

Add link to @gvanrossum's 2006 talk

Update 'VCS features'

---

content/deciding-factors/index.md

Update deciding factors

---

content/concurrent-development-of-consecutive-releases/index.md

Update 'concurrent dev of consecutive releases'

---

content/expanding-contracting-monorepos/index.md

Sorry to be trickling in these edits @paul-hammant! I'm submitting them via the Github UI and making the edits as I read

Update expanding/contracting monorepos

---

content/styles/index.md

I took the liberty to fix some typos and some sentences in the styles section. I hope you are ok with this.

Fix typos and some sentences

---

config.toml
themes/hugo-material-docs/layouts/partials/footer.html

Should fix Issues seen in: https://github.com/paul-hammant/tbd/issues/108

[FIX] Correction to footer Nav Buttons, fixing the order, and giving Context a prev button

---

content/_index.md

Introduction Typo Fix (rquires->requires)
